default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: transaction_example_dev